server:
  port: 8080 # ß╗¿ng dß╗Ñng chß║íy tr├¬n cß╗òng 8080
  servlet:
    context-path: /identity # ─É╞░ß╗¥ng dß║½n gß╗æc cß╗ºa API (VD: http://localhost:8080/identity/users)

spring:
  datasource:
    # URL kß║┐t nß╗æi ─æß║┐n MySQL. Port 3636 l├á cß╗òng ─æ├ú ─æ╞░ß╗úc map tß╗½ Docker ra m├íy thß║¡t.
    # ${DBMS_CONNECTION:...} gi├║p linh hoß║ít thay ─æß╗òi URL khi chß║íy tr├¬n server thß║¡t.
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3636/identity-servive}

    # T├ái khoß║ún v├á mß║¡t khß║⌐u kß║┐t nß╗æi Database
    username: ${DBMS_USER:root}
    password: ${DBMS_PASSWORD:lamdzbodoi}

    driver-class-name: "com.mysql.cj.jdbc.Driver"
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: "https://generativelanguage.googleapis.com"
        completions-path : "/v1beta/openai/chat/completions"
        options :
          model : gemini-3-flash-preview
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    sql:
      init:
        mode: always

  jpa:
    hibernate:
      # 'update': Hibernate sß║╜ tß╗▒ ─æß╗Öng so s├ính Entity v├á DB ─æß╗â th├¬m/sß╗¡a cß╗Öt m├á kh├┤ng x├│a dß╗» liß╗çu c┼⌐
      ddl-auto: update

    # 'show-sql: true': In c├íc c├óu lß╗çnh SQL m├á Hibernate thß╗▒c thi ra m├án h├¼nh console ─æß╗â tiß╗çn debug
    show-sql: true
    properties:
      hibernate:
        # Khai b├ío ph╞░╞íng ng├┤n SQL sß╗¡ dß╗Ñng cho MySQL
        dialect: org.hibernate.dialect.MySQLDialect

  spring:
    flyway:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      baseline-version: 1
logging:
  level:
    org.springframework.security: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true

jwt:
  # Kh├│a b├¡ mß║¡t (HS512) d├╣ng ─æß╗â k├╜ t├¬n l├¬n Token. Phß║úi giß╗» k├¡n kh├│a n├áy!
  signerKey: "a065bd796281e2a4388ebc7f7a3c41bba935512d5e51526e898235a6ad5b4142"

  # Thß╗¥i gian sß╗æng cß╗ºa Access Token (3600 gi├óy = 1 giß╗¥)
  valid-duration: 3600

  # Thß╗¥i gian tß╗æi ─æa ─æß╗â c├│ thß╗â d├╣ng Refresh Token (360.000 gi├óy = 100 giß╗¥)
  refreshable-duration: 360000

  outbound:
    identity:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: "http://localhost:3000/authenticate"
