@startuml
skinparam dpi 120
skinparam backgroundColor #FFFFFF
skinparam defaultFontSize 11
skinparam useCaseFontSize 11
skinparam actorFontSize 12

left to right direction

actor "Người dùng" as USER
actor "Quản trị viên" as ADMIN

rectangle "Cộng đồng" {
  (Tạo bài viết) as S1
  (Xem Feed) as S2
  (Xem bài viết chi tiết) as S3
  (Xoá bài viết) as S4
  (Tạo bình luận) as S5
  (Xem bình luận) as S6
  (Xoá bình luận) as S7
  (Thích bài viết) as S8
  (Bỏ thích bài viết) as S9
  (Theo dõi người dùng) as S10
  (Bỏ theo dõi) as S11
  (Xem danh sách theo dõi) as S12
  (Lưu bài viết) as S13
  (Bỏ lưu bài viết) as S14
  (Xem bài viết đã lưu) as S15
  (Upload ảnh) as S16

  USER --> S1
  USER --> S2
  USER --> S3
  USER --> S4
  USER --> S5
  USER --> S6
  USER --> S7
  USER --> S8
  USER --> S9
  USER --> S10
  USER --> S11
  USER --> S12
  USER --> S13
  USER --> S14
  USER --> S15
  USER --> S16

  ADMIN --> S4
  ADMIN --> S7
}

@enduml
